services:
  development:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    env_file:
      - .env
    environment:
      - LISTEN_PORT=${LISTEN_PORT}
      - ASPNETCORE_ENVIRONMENT=development
      - SYNCFUSION_LICENSE_KEY=${SYNCFUSION_LICENSE_KEY}
    working_dir: /app
    command: ["dotnet", "run"]
    profiles:
      - development

  production:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:80" # Changed port to avoid conflict
    env_file:
      - .env
    environment:
      - LISTEN_PORT=${LISTEN_PORT}
      - ASPNETCORE_ENVIRONMENT=production
      - SYNCFUSION_LICENSE_KEY=${SYNCFUSION_LICENSE_KEY}
    working_dir: /app/publish
    command: ["dotnet", "rino-syncfusion.dll"] # Ensure this matches your entry point
    profiles:
      - production
