services:
  syncfusion:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      LISTEN_PORT: ${LISTEN_PORT}
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://0.0.0.0:${LISTEN_PORT:-8080}"
      SYNCFUSION_LICENSE_KEY: ${SYNCFUSION_LICENSE_KEY}
    ports:
      - "${LISTEN_PORT:-8080}:${LISTEN_PORT:-8080}"
    profiles:
      - development
  
  production:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      LISTEN_PORT: ${LISTEN_PORT}
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://0.0.0.0:${LISTEN_PORT:-8080}"
      SYNCFUSION_LICENSE_KEY: ${SYNCFUSION_LICENSE_KEY}
    ports:
      - "${LISTEN_PORT:-8080}:${LISTEN_PORT:-8080}"
    profiles:
      - production